### ISSUE TITLE
Stuck at "found some mature content"

### ISSUE THREAD

**Issue by sirenmix** [ScienceDiscoverer/steamscrd#1] opened 2024-02-28 13:01 UTC
Hi !
I am trying to download all the screenshots from my account (1516 screenshots), but after the 240th first screenshots, I'm getting stuck at "Found some mature content! Feeding The Kinky Cookie to server in 2 sec..." and it keeps saying that but nothing happens and it isn't downloading anymore.

**Comment by ScienceDiscoverer** [comment] 2024-02-29 04:40
I just tried to download all my Witcher 3 screens that had plenty of restricted content in them, and "Kinky Cookie" worked with no issues. Can you give me your steam ID so that I can try to reproduce the issue?

**Comment by Moerderhoschi** [comment] 2024-03-17 10:55
@ScienceDiscoverer here you can reproduce this issue -> steamscrd.exe 76561198024994192 -spage=105

![image](https://github.com/ScienceDiscoverer/steamscrd/assets/163730007/7e7408b1-84bd-4434-bc28-99cfc5aa4f52)

**Comment by ScienceDiscoverer** [comment] 2024-03-19 09:00
> 76561198024994192

Thanks! I was able to reproduce it, and I now see exactly what is the problem. Problem is, if the screenshot itself is not rated as mature content, it won't be covered like this:

![image](https://github.com/ScienceDiscoverer/steamscrd/assets/29157485/44dc96ce-cb30-4910-940a-dd4c7ee84f09)

This case can be handled by my "Kinky Cookie".

But what I didn't know, is that if a game itself is "Adult Only", then ALL screenshots of this game will require use to be logged in to view, even if the screenshot itself is not marked as "mature content" and the preview can be seen... I didn't had any "Adult Only" game myself, so I didn't notice this...

I'm not sure if I can circumvent this with another Cookie without requiring login... But I'll try.

**Comment by Moerderhoschi** [comment] 2024-03-19 10:08
thank you for your quick reply. for me personal it would also be ok if you skip those screenshots.

**Comment by ScienceDiscoverer** [comment] 2024-03-19 16:05
> thank you for your quick reply. for me personal it would also be ok if you skip those screenshots.

I just released the updated version of the program - `1.0.1`. I did a few tests on your page 105 and was able to successfully download it and move on to page 106. I also fixed the annoying visual bug - error text over progress bar, visible in your screenshot.

I failed to download this "Adult Only" screenshots without login, but I also felt that implementing entire login pipeline for this utility was a bit overkill. So, I eventually figured out the compromise solution of just extracting 2 cookies from the mainstream browser.

I added instruction on how to extract 2 cookies required to download this screenshots into the `README.MD`.

Try it out and report here, so we can, possibly, close this issue!

**Comment by Moerderhoschi** [comment] 2024-03-19 20:13
i tried it but it dont work for me. when i start to catch page 105 he tells me to insert the cookie data and i did and then he stuck at

![image](https://github.com/ScienceDiscoverer/steamscrd/assets/163730007/a9a9e225-c772-4091-b266-a8fa603f53df)

after one min he stuck at 

![image](https://github.com/ScienceDiscoverer/steamscrd/assets/163730007/af77d1c6-d778-42de-ae4d-81b43dbba84c)

**Comment by ScienceDiscoverer** [comment] 2024-03-20 08:19
> i tired to open the screenshot in the browser but he dont let me because i'm from germany, maybe thats the problem here

Yea, I think this is the problem... The game's name is [HuniePop](https://steamcommunity.com/app/339800), and it is totally blocked in Germany?! WOW. I don't think this is really fixable...

So only 2 options, as I see it, is this:

1. Try to use some free VPN (like Proton)
2. I will have to detect the words "not available in your region" and propose to skip all screenshots from this game... This kind of sucks, because my perfectionism demands me to let the users download absolutely everything...

**Comment by Moerderhoschi** [comment] 2024-03-20 09:19
you are a great person and i really like your passion. for me personally it would be totally ok to skip those screenshots :-)

**Comment by ScienceDiscoverer** [comment] 2024-03-20 14:24
Check version 1.0.3, I added the `skip` one and `skipall` options in case when both "Kinky Cookie" and "Login Cookies" fails to get the screenshot.

**Comment by Moerderhoschi** [comment] 2024-03-21 08:08
ok, i run smooth the first 5.000 screenshots until page 101 then i had to insert my SteamLoginSecure and SteamSessionId an i did then he couldn't catch the screen and i answered skip. Then again he couldn't catch screenshot 5004 and the pgm terminated itself.

![image](https://github.com/ScienceDiscoverer/steamscrd/assets/163730007/f80b812d-4eaa-4ccd-9983-4d8f7eb46d61)

![image](https://github.com/ScienceDiscoverer/steamscrd/assets/163730007/7ce1af77-9fa9-42ed-bffe-12e0041f2300)

reproduce with -> steamscrd.exe 76561198024994192 -spage=101

but when i try it without the SteamLoginSecure and SessionId and make skip he skips and go on with the download

![image](https://github.com/ScienceDiscoverer/steamscrd/assets/163730007/abd185b1-b036-4ba0-be3c-09eeeb1f234b)

**Comment by ScienceDiscoverer** [comment] 2024-03-21 19:39
>ok now where i had the option retry or skip or : i tried it and entered skipall which was not shown but it seems to work and the pgm is still downloading. im happy with this solution :-)

The `skipall` option is displayed in colour that matches your background color (._. )
I will have to somehow set the BG colour to black in the beginning of program...

If you know 100% that your Login Cookies won't help, you can skip inputting them by pressing ENTER multiple times (IDK why it needs to be pressed 2 times). So, does page 105 still crashes even with `skipall`?

**Comment by Moerderhoschi** [comment] 2024-03-22 06:06
yes this works. when i dont enter the cookies and press enter to get to the options and then enter skipall everything runs fine until the end. like i wrote i'm totally happy with this solution. thank you :-)

**Closed** 2024-03-22 10:27 UTC
