### ISSUE TITLE
Download friends only screenshots using session cookie

### ISSUE THREAD

**Issue by Moerderhoschi** [ScienceDiscoverer/steamscrd#5] opened 2024-09-03 05:13 UTC
Hey it's me again, i like to download screenshots of my buddy which has screenshots for friends only. When i visit his Page in Chrome it shows me 107 Arma 3 Screenshots but the tool only downloads the 79 Public. i used the sls & sid parameter but it don't work for me. Any solution for me? Thank you!

steamscrd.exe 76561197971956363 -app=107410 -sls=765... -sid=ccd...

**Comment by ScienceDiscoverer** [comment] 2024-10-12 06:37
Sorry, but I can't reproduce this bug because of the privacy issue of needing the access to people's accounts.
I suspect that making our session cookie compromise work for all the people would be almost impossible task and/or will take a huge amount of time. So for now, I'll close this issue as not planned...

**Closed as not planned by ScienceDiscoverer** 2024-10-12 06:37 UTC
